# Generated by Django 6.1.2 on 2026-10-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the assignment was established.')),
                ('doctor', models.ForeignKey(help_text='The doctor assigned to the patient.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'verbose_name_plural': 'Patient-Doctor Mappings',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
