# Generated by Django 6.1.2 on 2026-10-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mappings', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(help_text='The patient being assigned a doctor.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='patientdoctormapping',
            index=models.Index(fields=['patient', 'doctor'], name='mappings_pa_patient_334947_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdoctormapping',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor_mapping'),
        ),
    ]
