# Generated by Django 6.1.2 on 2026-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full legal name of the patient.', max_length=150)),
                ('date_of_birth', models.DateField(help_text='Patient date of birth (cannot be in the future).')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text='Gender identity of the patient.', max_length=10)),
                ('contact_number', models.CharField(help_text='Primary contact telephone or mobile number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Patient contact email address.', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Residential address.')),
                ('medical_history', models.TextField(blank=True, help_text='Relevant medical conditions, allergies, or past treatments.')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
