# Generated by Django 6.1.2 on 2026-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name and title of the healthcare practitioner.', max_length=150)),
                ('specialization', models.CharField(db_index=True, help_text='Medical discipline or field of practice (e.g., Cardiology).', max_length=100)),
                ('contact_number', models.CharField(help_text='Primary contact telephone number.', max_length=20)),
                ('email', models.EmailField(db_index=True, help_text='Professional email address (must be unique).', max_length=255, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of clinical or professional experience.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the doctor is currently practicing/active.')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['specialization', 'is_active'], name='doctors_doc_special_78e3fa_idx')],
            },
        ),
    ]
